server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# hal 브라우저랑 actuator 라이브러리는 버전이 안맞아서 실습을 못해봄
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"